# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 14:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='application',
            name='application_reference',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('(\\w{2})([0-9]{7})')]),
        ),
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.CharField(blank=True, choices=[('ARC_REVIEW', 'ARC_REVIEW'), ('CANCELLED', 'CANCELLED'), ('CYGNUM_REVIEW', 'CYGNUM_REVIEW'), ('DRAFTING', 'DRAFTING'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION'), ('NOT_REGISTERED', 'NOT_REGISTERED'), ('REGISTERED', 'REGISTERED'), ('REJECTED', 'REJECTED'), ('SUBMITTED', 'SUBMITTED'), ('WITHDRAWN', 'WITHDRAWN')], max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(blank=True, choices=[('CHILDMINDER', 'CHILDMINDER'), ('NANNY', 'NANNY'), ('NURSERY', 'NURSERY'), ('SOCIAL_CARE', 'SOCIAL_CARE')], max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='change_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='childcare_address_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='childcare_address_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='childcare_training_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='childcare_training_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='criminal_record_check_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='criminal_record_check_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='cygnum_urn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='declarations_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='display_contact_details_on_web',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='first_aid_training_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='first_aid_training_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='information_correct_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='insurance_cover_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='insurance_cover_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='login_details_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='login_details_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='ofsted_visit_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_details_arc_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_details_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='references_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='share_info_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='application',
            name='suitable_declare',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterModelTable(
            name='application',
            table='NANNY_APPLICATION',
        ),
    ]
