# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180614_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='childcare_address_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='childcare_training_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='criminal_record_check_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='declarations_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_aid_training_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='insurance_cover_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='login_details_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='personal_details_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='references_status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50),
        ),
    ]
