# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20180615_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildcareAddress',
            fields=[
                ('childcare_address_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('street_line1', models.CharField(max_length=100)),
                ('street_line2', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('address_to_be_provided', models.NullBooleanField(default=None)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
            options={
                'db_table': 'CHILDCARE_APPLICATION',
            },
        ),
    ]
