# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_childcareaddress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='childcareaddress',
            table='CHILDCARE_ADDRESS',
        ),
    ]
