# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20180618_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='NannyApplication',
        ),
    ]
