# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20180618_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcareaddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childcareaddress',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childcareaddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childcareaddress',
            name='street_line1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childcareaddress',
            name='street_line2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='childcareaddress',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
