# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20180620_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildcareTraining',
            fields=[
                ('childcare_training_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('level_2_training', models.NullBooleanField(default=None)),
                ('common_core_training', models.NullBooleanField(default=None)),
                ('no_training', models.NullBooleanField(default=None)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.NannyApplication')),
            ],
            options={
                'db_table': 'CHILDCARE_TRAINING',
            },
        ),
        migrations.CreateModel(
            name='FirstAidTraining',
            fields=[
                ('first_aid_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('training_organisation', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('course_date', models.DateField()),
                ('show_certificate', models.NullBooleanField(default=None)),
                ('renew_certificate', models.NullBooleanField(default=None)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.NannyApplication')),
            ],
            options={
                'db_table': 'FIRST_AID_TRAINING',
            },
        ),
    ]
