# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_applicantpersonaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantHomeAddress',
            fields=[
                ('home_address_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('street_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('street_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address', models.NullBooleanField(default=None)),
                ('move_in_month', models.IntegerField(blank=True, null=True)),
                ('move_in_year', models.IntegerField(blank=True, null=True)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='application.NannyApplication')),
                ('personal_detail_id', models.ForeignKey(db_column='personal_detail_id', on_delete=django.db.models.deletion.CASCADE, to='application.ApplicantPersonalDetails')),
            ],
            options={
                'db_table': 'APPLICANT_HOME_ADDRESS',
            },
        ),
    ]
