# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-21 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_applicanthomeaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicanthomeaddress',
            name='childcare_address',
            field=models.NullBooleanField(default=None),
        ),
    ]
