# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-25 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_childcaretraining_firstaidtraining'),
        ('application', '0012_auto_20180625_1005'),
    ]

    operations = [
    ]
