# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-25 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_merge_20180625_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='middle_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
