# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-25 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20180625_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantpersonaldetails',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='applicantpersonaldetails',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='applicantpersonaldetails',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
