# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-21 14:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantHomeAddress',
            fields=[
                ('home_address_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('street_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('street_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address', models.NullBooleanField(default=None)),
                ('childcare_address', models.NullBooleanField(default=None)),
                ('move_in_month', models.IntegerField(blank=True, null=True)),
                ('move_in_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'APPLICANT_HOME_ADDRESS',
            },
        ),
        migrations.CreateModel(
            name='ApplicantPersonalDetails',
            fields=[
                ('personal_detail_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('birth_day', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'APPLICANT_PERSONAL_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='ChildcareAddress',
            fields=[
                ('childcare_address_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('street_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('street_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'CHILDCARE_ADDRESS',
            },
        ),
        migrations.CreateModel(
            name='NannyApplication',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('application_type', models.CharField(blank=True, choices=[('CHILDMINDER', 'CHILDMINDER'), ('NANNY', 'NANNY'), ('NURSERY', 'NURSERY'), ('SOCIAL_CARE', 'SOCIAL_CARE')], max_length=50)),
                ('application_status', models.CharField(blank=True, choices=[('ARC_REVIEW', 'ARC_REVIEW'), ('CANCELLED', 'CANCELLED'), ('CYGNUM_REVIEW', 'CYGNUM_REVIEW'), ('DRAFTING', 'DRAFTING'), ('FURTHER_INFORMATION', 'FURTHER_INFORMATION'), ('NOT_REGISTERED', 'NOT_REGISTERED'), ('REGISTERED', 'REGISTERED'), ('REJECTED', 'REJECTED'), ('SUBMITTED', 'SUBMITTED'), ('WITHDRAWN', 'WITHDRAWN')], max_length=50)),
                ('cygnum_urn', models.CharField(blank=True, max_length=50)),
                ('login_details_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50)),
                ('login_details_arc_flagged', models.BooleanField(default=False)),
                ('personal_details_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50)),
                ('personal_details_arc_flagged', models.BooleanField(default=False)),
                ('childcare_address_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50)),
                ('childcare_address_arc_flagged', models.BooleanField(default=False)),
                ('first_aid_training_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50)),
                ('first_aid_training_arc_flagged', models.BooleanField(default=False)),
                ('childcare_training_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50)),
                ('childcare_training_arc_flagged', models.BooleanField(default=False)),
                ('criminal_record_check_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50)),
                ('criminal_record_check_arc_flagged', models.BooleanField(default=False)),
                ('insurance_cover_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50)),
                ('insurance_cover_arc_flagged', models.BooleanField(default=False)),
                ('declarations_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50)),
                ('references_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('FLAGGED', 'FLAGGED')], default='NOT_STARTED', max_length=50)),
                ('share_info_declare', models.NullBooleanField(default=None)),
                ('display_contact_details_on_web', models.NullBooleanField(default=None)),
                ('suitable_declare', models.NullBooleanField(default=None)),
                ('information_correct_declare', models.NullBooleanField(default=None)),
                ('change_declare', models.NullBooleanField(default=None)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('application_reference', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('(\\w{2})([0-9]{7})')])),
                ('ofsted_visit_email_sent', models.DateTimeField(blank=True, null=True)),
                ('address_to_be_provided', models.NullBooleanField(default=None)),
            ],
            options={
                'db_table': 'NANNY_APPLICATION',
            },
        ),
        migrations.AddField(
            model_name='childcareaddress',
            name='application_id',
            field=models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='nanny_models.NannyApplication'),
        ),
        migrations.AddField(
            model_name='applicantpersonaldetails',
            name='application_id',
            field=models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='nanny_models.NannyApplication'),
        ),
        migrations.AddField(
            model_name='applicanthomeaddress',
            name='application_id',
            field=models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='nanny_models.NannyApplication'),
        ),
        migrations.AddField(
            model_name='applicanthomeaddress',
            name='personal_detail_id',
            field=models.ForeignKey(db_column='personal_detail_id', on_delete=django.db.models.deletion.CASCADE, to='nanny_models.ApplicantPersonalDetails'),
        ),
    ]
